image:
  file: .gitpod.Dockerfile

tasks:
- init: mysqladmin --wait --count 3 ping && mysql < deployments/init.sql
  command: make watcher
- command: getenvoy run standard:1.18.2 -- --config-path deployments/envoy.yaml 
- init: cd web && yarn
  command: cd web && yarn start

vscode:
  extensions:
    - zxh404.vscode-proto3
    - golang.go

github:
  prebuilds:
    addBadge: true

ports:
- port: 3000
  onOpen: ignore
- port: 3306
  onOpen: ignore
- port: 8080
  onOpen: ignore
- port: 9901
  onOpen: ignore
- port: 9000
  onOpen: ignore

