image:
  file: .gitpod.Dockerfile

tasks:
- init: mysql < deployments/init.sql
  command: make watcher
- command: getenvoy run standard:1.18.2 -- --version
- init: cd web && yarn

vscode:
  extensions:
    - zxh404.vscode-proto3
    - golang.go

github:
  prebuilds:
    addBadge: true
