image:
  file: .gitpod.Dockerfile

tasks:
- init: mysqladmin --wait --count 3 ping && mysql < deployments/init.sql
- init: mysqladmin --wait --count 3 ping
  command: make watcher
- init: mysqladmin --wait --count 3 ping
  command: make subscription
- command: func-e run -c deployments/envoy.yaml
- init: cd web && yarn
  command: yarn start

vscode:
  extensions:
    - zxh404.vscode-proto3
    - golang.go

github:
  prebuilds:
    addBadge: true

ports:
- port: 3000
  onOpen: ignore
- port: 3306
  onOpen: ignore
- port: 8080
  onOpen: ignore
- port: 9901
  onOpen: ignore
- port: 9000
  onOpen: ignore
- port: 9001
  onOpen: ignore

