// Code generated by MockGen. DO NOT EDIT.
// Source: persistent.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	proto "google.golang.org/protobuf/proto"
)

// Mockpersistent is a mock of persistent interface.
type Mockpersistent struct {
	ctrl     *gomock.Controller
	recorder *MockpersistentMockRecorder
}

// MockpersistentMockRecorder is the mock recorder for Mockpersistent.
type MockpersistentMockRecorder struct {
	mock *Mockpersistent
}

// NewMockpersistent creates a new mock instance.
func NewMockpersistent(ctrl *gomock.Controller) *Mockpersistent {
	mock := &Mockpersistent{ctrl: ctrl}
	mock.recorder = &MockpersistentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockpersistent) EXPECT() *MockpersistentMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockpersistent) Create(arg0 proto.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockpersistentMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockpersistent)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *Mockpersistent) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockpersistentMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mockpersistent)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *Mockpersistent) Get(arg0 string) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpersistentMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockpersistent)(nil).Get), arg0)
}

// List mocks base method.
func (m *Mockpersistent) List(arg0, arg1 int) ([]proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockpersistentMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Mockpersistent)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *Mockpersistent) Update(arg0 string, arg1 *field_mask.FieldMask, arg2 proto.Message) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockpersistentMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*Mockpersistent)(nil).Update), arg0, arg1, arg2)
}
