// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatcherServiceClient interface {
	CreateWatcher(ctx context.Context, in *CreateWatcherRequest, opts ...grpc.CallOption) (*Watcher, error)
	DeleteWatcher(ctx context.Context, in *DeleteWatcherRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetWatcher(ctx context.Context, in *GetWatcherRequest, opts ...grpc.CallOption) (*Watcher, error)
	ListWatcher(ctx context.Context, in *ListWatcherRequest, opts ...grpc.CallOption) (*ListWatcherResponse, error)
	UpdateWatcher(ctx context.Context, in *UpdateWatcherRequest, opts ...grpc.CallOption) (*Watcher, error)
}

type watcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherServiceClient(cc grpc.ClientConnInterface) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) CreateWatcher(ctx context.Context, in *CreateWatcherRequest, opts ...grpc.CallOption) (*Watcher, error) {
	out := new(Watcher)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.egosla.api.WatcherService/CreateWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) DeleteWatcher(ctx context.Context, in *DeleteWatcherRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.egosla.api.WatcherService/DeleteWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) GetWatcher(ctx context.Context, in *GetWatcherRequest, opts ...grpc.CallOption) (*Watcher, error) {
	out := new(Watcher)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.egosla.api.WatcherService/GetWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) ListWatcher(ctx context.Context, in *ListWatcherRequest, opts ...grpc.CallOption) (*ListWatcherResponse, error) {
	out := new(ListWatcherResponse)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.egosla.api.WatcherService/ListWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherServiceClient) UpdateWatcher(ctx context.Context, in *UpdateWatcherRequest, opts ...grpc.CallOption) (*Watcher, error) {
	out := new(Watcher)
	err := c.cc.Invoke(ctx, "/nokamoto.github.com.egosla.api.WatcherService/UpdateWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatcherServiceServer is the server API for WatcherService service.
// All implementations must embed UnimplementedWatcherServiceServer
// for forward compatibility
type WatcherServiceServer interface {
	CreateWatcher(context.Context, *CreateWatcherRequest) (*Watcher, error)
	DeleteWatcher(context.Context, *DeleteWatcherRequest) (*empty.Empty, error)
	GetWatcher(context.Context, *GetWatcherRequest) (*Watcher, error)
	ListWatcher(context.Context, *ListWatcherRequest) (*ListWatcherResponse, error)
	UpdateWatcher(context.Context, *UpdateWatcherRequest) (*Watcher, error)
	mustEmbedUnimplementedWatcherServiceServer()
}

// UnimplementedWatcherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWatcherServiceServer struct {
}

func (UnimplementedWatcherServiceServer) CreateWatcher(context.Context, *CreateWatcherRequest) (*Watcher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWatcher not implemented")
}
func (UnimplementedWatcherServiceServer) DeleteWatcher(context.Context, *DeleteWatcherRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWatcher not implemented")
}
func (UnimplementedWatcherServiceServer) GetWatcher(context.Context, *GetWatcherRequest) (*Watcher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWatcher not implemented")
}
func (UnimplementedWatcherServiceServer) ListWatcher(context.Context, *ListWatcherRequest) (*ListWatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatcher not implemented")
}
func (UnimplementedWatcherServiceServer) UpdateWatcher(context.Context, *UpdateWatcherRequest) (*Watcher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWatcher not implemented")
}
func (UnimplementedWatcherServiceServer) mustEmbedUnimplementedWatcherServiceServer() {}

// UnsafeWatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServiceServer will
// result in compilation errors.
type UnsafeWatcherServiceServer interface {
	mustEmbedUnimplementedWatcherServiceServer()
}

func RegisterWatcherServiceServer(s grpc.ServiceRegistrar, srv WatcherServiceServer) {
	s.RegisterService(&WatcherService_ServiceDesc, srv)
}

func _WatcherService_CreateWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).CreateWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.egosla.api.WatcherService/CreateWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).CreateWatcher(ctx, req.(*CreateWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_DeleteWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).DeleteWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.egosla.api.WatcherService/DeleteWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).DeleteWatcher(ctx, req.(*DeleteWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_GetWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).GetWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.egosla.api.WatcherService/GetWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).GetWatcher(ctx, req.(*GetWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_ListWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).ListWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.egosla.api.WatcherService/ListWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).ListWatcher(ctx, req.(*ListWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatcherService_UpdateWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).UpdateWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nokamoto.github.com.egosla.api.WatcherService/UpdateWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).UpdateWatcher(ctx, req.(*UpdateWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatcherService_ServiceDesc is the grpc.ServiceDesc for WatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nokamoto.github.com.egosla.api.WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWatcher",
			Handler:    _WatcherService_CreateWatcher_Handler,
		},
		{
			MethodName: "DeleteWatcher",
			Handler:    _WatcherService_DeleteWatcher_Handler,
		},
		{
			MethodName: "GetWatcher",
			Handler:    _WatcherService_GetWatcher_Handler,
		},
		{
			MethodName: "ListWatcher",
			Handler:    _WatcherService_ListWatcher_Handler,
		},
		{
			MethodName: "UpdateWatcher",
			Handler:    _WatcherService_UpdateWatcher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
