name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: echo /home/runner/go/bin >> ${GITHUB_PATH}
      - run: sudo apt install -y clang-format protobuf-compiler
      - run: make
      - run: git diff --exit-code -- . ':(exclude)go.sum'
